remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" #"default" ,"aqua", "air", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site settings
title : "Good Advice"
subtitle : "Scientific Creativity"
logo : "/assets/images/icons8-stabilimento-chimico-3-48.png"
email: gianmarco.polotti@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
repository  : "good-advice/good-advice.github.io"
words_per_minute: 200
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
    staticman_url: https://good-advice-blog.herokuapp.com/v2/entry/good-advice/good-advice.github.io/master/comments
reCaptcha:
   siteKey: 6LcSYAEVAAAAAKIALcmFmi2-9ho5xxpYOkJvugN-
   secret: NoM/ICVK+NCJlAuf5ZWwqS2TpFepjN5w5Kg0ZUDLt0Sf1/UYvTD/z2ONDDTZ0+UQEDuTN4hhE51Mbqq2lPNjiuDwuFNRAfmQQnowOf/+lk3S/Z+9zVcdAWaYji93vcHWH7+9fsvOht1MDw4TRgDNn6bk/Sx+BjdxD4e+xVCdjr+vRkQNLPzlvnHOngFFav58xp0lX8Fdytjz6K/FPDWWP6XZ0QWjodU/CkxUO5Zv44UCHcnKsCm5DL/r8vO9j7aQfJdDgpccGj5HEsl/mt+kIRh1dFCeTLUN0avka1ia4hdAyB7OB6Pzm4BDvXill9N5Dbrmoz+EDvkC+aaKrhloHR3pVbPIYPn4DLqFPtjHpzZ/WSH3tMOkPKcZaojZr2WyeXeQtKQr70L2hpBvYW1nteFKkZu7W2nrLyRrFNWmRAewVQU7x7wKbB8wlZtH9ugX2eBGoBWA8x8C9JxxI8KSvv9hV3le6qr0w758uj49DSkh9Dj+yG3K5j+Y6I/rNf5MK0XS1bx/qzKHVAxhSG+ESrVzelIVs8GpnIeNqpWVnkdSSK7BCQaQOzIsm6zhMp1wp8sGCbrfeio0ia0hlJYKjABI9LcL31Q/PesVYtLn3HxZVEDbcA3U0rL8aVtJpSGSnj+C5vGIVQMFJ8gdI4aQJbOeKlfu7/DAqni8t0b0l9Q=

# Social Sharing
twitter_username : username
github_username : polgia0
search: true

# Reading Files
include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gianmarco Polotti"
  avatar : "/assets/images/me_circolare.png"
  bio    : "Chemical Process & Data Analyst"
  links:
    #- label: "Website"
      #icon: "fas fa-fw fa-link"
      #url: "https://"
    - label: "Linked-in"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/gianmarco-polotti-ab0136/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/good-advice/good-advice.github.io"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/good-advice/good-advice.github.io"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
